name: Cache Test Workflow
on: push
jobs:
  cache-test:
    name: Test Caching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache dependencies
        id: cache-e3e5a2c
        uses: actions/cache@v4
        with:
          path: ~/.cache/test-deps
          key: cache-e3e5a2c
      
      - name: prime-cache-e3e5a2c
        run: |
          if [[ "${{ steps.cache-e3e5a2c.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit: cache-e3e5a2c"
          else
            echo "Cache miss: cache-e3e5a2c"
            mkdir -p ~/.cache/test-deps
            echo "test" > ~/.cache/test-deps/data.txt
          fi
